name: geoform_example
description: Demonstrates how to use the geoform plugin.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  geoform:
    path: ../
  flutter_map_tile_caching: ^8.0.0

  cupertino_icons: ^1.0.2
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
