name: geoform
description: Flutter widget to work with dynamic forms that have a geo-spatial reference asociated with the form. This tool can be used to group and simplify the work with these forms.
version: 0.0.6-beta.4
homepage: https://github.com/mixinlab/geoform

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  flutter_map: ^3.0.0
  flutter_map_location_marker: ^5.0.0
  flutter_map_tile_caching: ^6.1.0
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^2.1.0
  latlong2: ^0.8.1
  location: ^4.3.0
  positioned_tap_detector_2: ^1.0.4
  vector_map_tiles: ^3.1.4
  vector_tile_renderer: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: cc.innovalab.geoform.geoform
        pluginClass: GeoformPlugin
      ios:
        pluginClass: GeoformPlugin
      linux:
        pluginClass: GeoformPlugin
      web:
        pluginClass: GeoformWeb
        fileName: geoform_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
