name: geoform
description: Flutter widget to work with dynamic forms that have a geo-spatial reference asociated with the form. This tool can be used to group and simplify the work with these forms.
version: 0.0.8-beta.2
homepage: https://github.com/mixinlab/geoform

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter_bloc: ^8.1.2
  collection: ^1.17.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_map_tile_caching: ^8.0.0
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^4.0.4
  latlong2: ^0.8.1
  location: ^4.3.0
  positioned_tap_detector_2: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cc.innovalab.geoform.geoform
        pluginClass: GeoformPlugin
      ios:
        pluginClass: GeoformPlugin
      linux:
        pluginClass: GeoformPlugin
      web:
        pluginClass: GeoformWeb
        fileName: geoform_web.dart
